# Heap terminal palette (default variant)

bold-is-bright = true

background = #121212
foreground = #d4d4d4

cursor-color = #aadadb
cursor-text = #121212

selection-background = #264f78
selection-foreground = #c2ffdf

palette = 0=#0a0a0a
palette = 1=#FF204E
palette = 2=#6a9955
palette = 3=#DFFF00
palette = 4=#1398b9
palette = 5=#aadadb
palette = 6=#8fbcbb
palette = 7=#d4d4d4
palette = 8=#606060
palette = 9=#FF204E
palette = 10=#afffaf
palette = 11=#DCFFB7
palette = 12=#98e4ff
palette = 13=#aadadb
palette = 14=#aadadb
palette = 15=#ffffff
