# Heap terminal palette (dark variant)

bold-is-bright = true

background = #09090b
foreground = #ffffff

cursor-color = #3fb6a6
cursor-text = #09090b

selection-background = #254147
selection-foreground = #d5d5d5

palette = 0=#09090b
palette = 1=#e06c75
palette = 2=#3fb6a6
palette = 3=#dfff00
palette = 4=#6eafad
palette = 5=#e3ecf6
palette = 6=#8996a3
palette = 7=#c0c0c0
palette = 8=#808080
palette = 9=#e06c75
palette = 10=#eaf0e5
palette = 11=#dfff00
palette = 12=#6eafad
palette = 13=#e3ecf6
palette = 14=#eaf0e5
palette = 15=#ffffff
