-- Highlight group: treesitter
local M = {}

M.apply_treesitter_highlights = function(colors, opts)
	-- Treesitter highlights
	local treesitter_highlights = {
		["@annotation"] = { fg = colors.tag },
		["@attribute"] = { fg = colors.tag_attribute },
		["@boolean"] = { fg = colors.number },
		["@character"] = { fg = colors.string },
		["@comment"] = { fg = colors.comment, italic = true },
		["@conditional"] = { fg = colors.control_flow },
		["@constant"] = { fg = colors.constant_builtin },
		["@constant.builtin"] = { fg = colors.constant_builtin },
		["@constant.macro"] = { fg = colors.constant_user },
		["@constructor"] = { fg = colors.class_name },
		["@error"] = { fg = colors.invalid },
		["@exception"] = { fg = colors.keyword },
		["@field"] = { fg = colors.property },
		["@function"] = { fg = colors.function_name },
		["@function.builtin"] = { fg = colors.library_function },
		["@function.call"] = { fg = colors.function_name },
		["@function.macro"] = { fg = colors.keyword },
		["@include"] = { fg = colors.keyword },
		["@keyword"] = { fg = colors.keyword },
		["@keyword.function"] = { fg = colors.storage },
		["@keyword.operator"] = { fg = colors.operators },
		["@keyword.return"] = { fg = colors.term_red },
		["@label"] = { fg = colors.tag_attribute },
		["@method"] = { fg = colors.function_name },
		["@method.call"] = { fg = colors.function_name },
		["@namespace"] = { fg = colors.class_name },
		["@number"] = { fg = colors.number },
		["@operator"] = { fg = colors.operators },
		["@parameter"] = { fg = colors.parameter },
		["@parameter.reference"] = { fg = colors.parameter },
		["@property"] = { fg = colors.property },
		["@punctuation.bracket"] = { fg = colors.punctuation },
		["@punctuation.delimiter"] = { fg = colors.punctuation },
		["@punctuation.special"] = { fg = colors.punctuation },
		["@repeat"] = { fg = colors.control_flow },
		["@string"] = { fg = colors.string },
		["@string.escape"] = { fg = colors.string_escape },
		["@string.special"] = { fg = colors.string_escape },
		["@symbol"] = { fg = colors.constant_builtin },
		["@tag"] = { fg = colors.tag },
		["@tag.attribute"] = { fg = colors.tag_attribute },
		["@tag.delimiter"] = { fg = colors.tag_start_end },
		["@text"] = { fg = colors.fg },
		["@text.strong"] = { fg = colors.markdown_italic, bold = true },
		["@text.emphasis"] = { fg = colors.markdown_italic, italic = true },
		["@text.underline"] = { underline = true },
		["@text.strike"] = { strikethrough = true },
		["@text.title"] = { fg = colors.markdown_heading, bold = true },
		["@text.literal"] = { fg = colors.string },
		["@text.quote"] = { fg = colors.comment },
		["@text.uri"] = { fg = colors.markdown_link, underline = true },
		["@text.math"] = { fg = colors.number },
		["@text.environment"] = { fg = colors.tag },
		["@text.environment.name"] = { fg = colors.tag },
		["@text.reference"] = { fg = colors.markdown_link },
		["@text.todo"] = { fg = colors.term_yellow },
		["@text.note"] = { fg = colors.term_cyan },
		["@text.warning"] = { fg = colors.term_yellow },
		["@text.danger"] = { fg = colors.term_red },
		-- Neovim 0.11+ markdown capture names
		["@markup"] = { fg = colors.fg },
		["@markup.strong"] = { fg = colors.markdown_italic, bold = true },
		["@markup.italic"] = { fg = colors.markdown_italic, italic = true },
		["@markup.underline"] = { underline = true },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.heading"] = { fg = colors.markdown_heading, bold = true },
		["@markup.raw"] = { fg = colors.string },
		["@markup.quote"] = { fg = colors.comment },
		["@markup.math"] = { fg = colors.number },
		["@markup.environment"] = { fg = colors.tag },
		["@markup.environment.name"] = { fg = colors.tag },
		["@markup.link"] = { fg = colors.markdown_link, underline = true },
		["@markup.link.url"] = { fg = colors.markdown_link, underline = true },
		["@markup.link.label"] = { fg = colors.markdown_link },
		["@markup.list"] = { fg = colors.markdown_list },
		["@type"] = { fg = colors.storage_type },
		["@type.builtin"] = { fg = colors.library_type },
		["@variable"] = { fg = colors.variable },
		["@variable.builtin"] = { fg = colors.this_keyword },

		-- Additional Treesitter highlights for enhanced syntax support
		["@module"] = { fg = colors.class_name },
		["@module.builtin"] = { fg = colors.library_type },
		["@property.class"] = { fg = colors.property },
		["@property.enum"] = { fg = colors.property },
		["@type.definition"] = { fg = colors.storage_type },
		["@type.qualifier"] = { fg = colors.storage },
		["@storageclass"] = { fg = colors.storage },
		["@storageclass.lifetime"] = { fg = colors.storage },
		["@lsp.type.lifetime"] = { link = "@storageclass.lifetime" },
		["@lsp.typemod.variable.constant"] = { link = "@constant" },
		["@lsp.typemod.variable.readonly"] = { fg = colors.constant_builtin },
		["@lsp.typemod.property.constant"] = { link = "@constant" },
		["@lsp.typemod.property.readonly"] = { fg = colors.property },
		["@lsp.typemod.function.associated"] = { link = "@function" },
		["@lsp.typemod.keyword.injected"] = { fg = colors.keyword },
		["@lsp.typemod.string.injected"] = { fg = colors.string },
		["@lsp.typemod.type.injected"] = { fg = colors.storage_type },
		["@string.regex"] = { fg = colors.string_escape },
		["@string.pattern"] = { fg = colors.string_escape },
		["@variable.parameter"] = { fg = colors.parameter },
		["@variable.member"] = { fg = colors.property },

		-- LSP Semantic Highlighting
		["@lsp.type.class"] = { link = "@type" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.decorator"] = { link = "@constant" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "@constant" },
		["@lsp.type.function"] = { link = "@function" },
		["@lsp.type.interface"] = { link = "@type" },
		["@lsp.type.macro"] = { link = "@function.macro" },
		["@lsp.type.method"] = { link = "@function" },
		["@lsp.type.namespace"] = { link = "@namespace" },
		["@lsp.type.parameter"] = { link = "@parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.struct"] = { link = "@type" },
		["@lsp.type.typeAlias"] = { link = "@type" },
		["@lsp.type.variable"] = { link = "@variable" },
		-- Extended LSP semantic highlighting
		["@lsp.type.commentBlock"] = { link = "@comment" },
		["@lsp.type.decoratorMethod"] = { link = "@function" },
		["@lsp.type.derive"] = { link = "@keyword" },
		["@lsp.type.generic"] = { link = "@type" },
		["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
		["@lsp.type.typeParameter"] = { link = "@type.definition" },
	}

	for hl_name, hl_def in pairs(treesitter_highlights) do
		vim.api.nvim_set_hl(0, hl_name, hl_def)
	end
end

-- Apply git related highlights

function M.apply(colors, opts)
	M.apply_treesitter_highlights(colors, opts)
end

return M
