# vim:ft=kitty

## name:     Heap
## author:   Heap
## license:  MIT

foreground              #d4d4d4
background              #121212
selection_foreground    #c2ffdf
selection_background    #264f78

cursor                  #aadadb
cursor_text_color       #121212

scrollbar_handle_color  #606060
scrollbar_track_color   #2a2a2a

url_color               #DFFF00

active_border_color     #aadadb
inactive_border_color   #606060
bell_border_color       #DFFF00

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #d4d4d4
active_tab_background   #121212
inactive_tab_foreground #8fbcbb
inactive_tab_background #2a2a2a
tab_bar_background      #1a1a1a

color0  #0a0a0a
color8  #606060

color1  #FF204E
color9  #FF204E

color2  #6a9955
color10 #afffaf

color3  #DFFF00
color11 #DCFFB7

color4  #1398b9
color12 #98e4ff

color5  #aadadb
color13 #aadadb

color6  #8fbcbb
color14 #aadadb

color7  #d4d4d4
color15 #ffffff
