# vim:ft=kitty

## name:     Heap Dark
## author:   Heap
## license:  MIT

foreground              #ffffff
background              #09090b
selection_foreground    #d5d5d5
selection_background    #254147

cursor                  #3fb6a6
cursor_text_color       #09090b

scrollbar_handle_color  #808080
scrollbar_track_color   #1e1e1e

url_color               #dfff00

active_border_color     #6eafad
inactive_border_color   #808080
bell_border_color       #dfff00

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #ffffff
active_tab_background   #09090b
inactive_tab_foreground #808080
inactive_tab_background #1e1e1e
tab_bar_background      #151515

color0  #09090b
color8  #808080

color1  #e06c75
color9  #e06c75

color2  #3fb6a6
color10 #eaf0e5

color3  #dfff00
color11 #dfff00

color4  #6eafad
color12 #6eafad

color5  #e3ecf6
color13 #e3ecf6

color6  #8996a3
color14 #eaf0e5

color7  #c0c0c0
color15 #ffffff
